### ISSUE TITLE
Not a single video opens.

### ISSUE THREAD

**Issue by majoraswrath360** [add-ons/plugin.video.viervijfzes#106]
The app was working fine on google TV. But recently tried launching it again but whatever video you try to open it just errors or doesn't open. Tried removing and reinstalling the plugin, but nothing seems to resolve the issue.

**Comment by michaelarnauts** [comment]
It's working fine on my CCWGTV. I'll need the Kodi logs to know what's going on.

**Comment by michaelarnauts** [comment]
I'm unable to reproduce this.
