### ISSUE TITLE
Alex Agnew´s Fear factor

### ISSUE THREAD

**Issue by Sorcerer1990** [add-ons/plugin.video.viervijfzes#110]
None of the episodes of "Alex Agnew´s Fear Factor" will play. Other shows work perfect.

**To Reproduce**
1. Go to "Alex Agnew´s Fear Factor"
2. Click any episode
3. Will not play 

**Expected behavior**
Expect the show to play.

**System**
 - Addon version: 0.4.8+matrix.1
 - Kodi version: 
 - Inputstream adaptive version:
 - Operating System (Android / LibreElec / OSMC / ...): Android
 - Special Hardware (RPI / Vero4K+ / ...):

**Additional context**

**Comment by michaelarnauts** [comment]
Note to self: It's probably related to the '-symbol.

**Comment by aGreatDay** [comment]
Last episode (6x05.) of 'The sky is the limit' doesn't seem to work too.

**Comment by mediaminister** [comment]
It seems GoPlay introduced a new streaming format: 1080p (unprotected) MPEG-DASH.

**Comment by michaelarnauts** [comment]
@aGreatDay @Sorcerer1990 can you try with this build? (for matrix)

[plugin.video.viervijfzes-0.4.8+matrix.1.zip](https://github.com/add-ons/plugin.video.viervijfzes/files/10236211/plugin.video.viervijfzes-0.4.8%2Bmatrix.1.zip)

**Comment by aGreatDay** [comment]
@michaelarnauts works for me! Thanks!
