### ISSUE TITLE
Availability of v0.4.11 for Kodi not running Matrix

### ISSUE THREAD

**Issue by PeterCloet** [add-ons/plugin.video.viervijfzes#132]
One of my mediaplayers is still running LibreElec 9.2.8 (Kodi Leia 18.9).
I was running the GoPlay add-on with v0.4.10 (with matrix.1) but this has stopped working.
When I try to update the GoPlay add-on to v0.4.11+matrix.1 (the only version I can find on the site), I get a compatibility error with the Python version installed.
Is there a v0.4.11 available for non-Matrix Kodi installations?

**Comment by michaelarnauts** [comment]
No, Kodi Leia (that uses Python 2) isn't supported anymore. You should really consider upgrading to a more recent Kodi.
