### ISSUE TITLE
Goplay addon doesn't seem to work anymore, API returning 404 errors

### ISSUE THREAD

**Issue by z3r0bytes** [add-ons/plugin.video.viervijfzes#142]
**Describe the bug**
Cannot view anything anymore, and gives errors when trying to load recommendations or popular

**To Reproduce**
1. Open Goplay addon
2. Try to play anything
3. Doesn't work anymore :(

**Expected behavior**
Should be able to list all programs and play them

**Screenshots**
None

**Logs**
I saw in the logs a lot of 404's when calling the API's, I assume this addon is broken for everyone now. 

**System**
 - Addon version:  0.4.11+matrix.1
 - Kodi version: 21.1
 - Operating System (Windows / Mac OS / Android / LibreElec / OSMC / ...): Android OS (nVidia Shield)

**Comment by PeterCloet** [comment]
The add-on has been broken for a while now and I don't believe it will be fixed.
However, there is an alternative add-on available [here](https://github.com/add-ons/plugin.video.goplay).
This one is working perfectly except for some streams on ARM-machines where VMP has been activated but that is beyong the author's possibility to solve (i.e. is an Android/Google issue).

**Comment by z3r0bytes** [comment]
Aaaah, makes sense, thanks :)
