### ISSUE TITLE
Unable to access any content: either "GoPlay fout" or empty list

### ISSUE THREAD

**Issue by roelschroeven** [add-ons/plugin.video.viervijfzes#143]
**Describe the bug**
Whenever I want to access GoPlay content, I get either a message "GoPlay fout" "Controleer het log voor meer informatie", or an empty list. As a result, I'm unable to access or play any content.
When I try to request the catalogue, I get a message "GoPlay fout" "Controleer het log voor meer informatie". The same when I go to Kanalen -> select one of the channels (e.g. Play4) -> Tv-gids voor Play4 -> select a date. Other methods of trying to access programs result in an empty list. 

I'm new to the Kodi GoPlay; I only installed it a few weeks ago, and I'm never been able to actually watch anything with it. I have delayed writing a bug report since I was hoping it was just a temporary problem. It has become clear now that the problem is not just a glitch though.

**To Reproduce**
There are different methods to reproduce. First via Kanalen / Tv-gids:
1. Select Kanalen
2. Select one of the channels, e.g. Play4
3. Select Tv-gids voor Play4
4. Select one of the dates in list
5. -> I get message "GoPlay fout" "Controleer het log voor meer informatie"

Or via Kanalen / Catalogus:
1. Select Kanalen
2. Select one of the channels, e.g. Play4
3. Select Catalogus voor Play4
4. -> I get an empty list

Or directly via Catalogus:
1. Select Catalogus
2. -> I get message "GoPlay fout" "Controleer het log voor meer informatie"

Or via A-Z:
1. Select A-Z
2. -> I get an empty list

**Expected behavior**
I expect to get a list of programs to watch.

**Logs**
https://paste.kodi.tv/ivazozewig.kodi

**System**
 - Addon version: v0.4.11+matrix.1
 - Kodi version: 21.0 (21.0.0) Git:20240406-60c4500054
 - Inputstream adaptive version: v21.5.5
 - Operating System (Windows / Mac OS / Android / LibreElec / OSMC / ...): Windows 11 (but I've also tried on Windows 10 and on LibreELEC on a RPI, all with the same result)
 - Special Hardware (RPI / Vero4K+ / ...):

**Additional context**
I had a look at the log file and noticed a couple of things:

At some point there's this line:
2024-10-20 16:20:25.899 T:16292   debug <CSettingsManager>: requested setting (credentials_hash) was not found.
That looks like it might indicate that I haven't entered my GoPlay credentials. I double-checked that I entered the correct credentials, but that didn't change anything.

Somewhat later there's this line; this one seems more important: 
2024-10-20 16:20:26.060 T:16292   debug <general>: [plugin.video.viervijfzes] [urllib3.connectionpool] https://www.goplay.be:443 "GET /api/content_tree HTTP/1.1" 404 None
It looks like we get a "Page not found". Indeed, if I try to open that URL (https://www.goplay.be:443/api/content_tree), either with curl (from a WSL shell) or from a browser (even when logged in into GoPlay), I get a 404 HTTP error too. It seems the problem is not isolated to Kodi. Indeed, it looks like the API that the Kodi GoPlay plugin is trying to use doesn't work. But then nobody would be able to use the plugin, and there would be much more bug reports. So it seems somehow something is different in my setup, but I have no idea what that could be. Is there anything else I can try to find out what exactly is going wrong?

**Comment by PeterCloet** [comment]
The add-on has been broken for a while now and I don't believe it will be fixed.
However, there is an alternative add-on available [here](https://github.com/add-ons/plugin.video.goplay).
This one is working perfectly except for some streams on ARM-machines where VMP has been activated but that is beyong the author's possibility to solve (i.e. is an Android/Google issue).

**Please keep this issue in status "OPEN" so we don't have to repeat this answer. ;-)**

**Comment by roelschroeven** [comment]
Ha, yes, that works, thank you.

Wouldn't it a good idea to mention that in the README and/or the wiki?

**Comment by PeterCloet** [comment]
Yes, that would be a good idea.
Unfortunately, I'm not able to edit the readme... I can only fork the project.
@mediaminister : Are you able to edit the readme?

**Comment by mediaminister** [comment]
Done.
I guess @michaelarnauts is the only one that can archive this repo so it becomes read-only.

**Comment by michaelarnauts** [comment]
> Done. I guess @michaelarnauts is the only one that can archive this repo so it becomes read-only.

I'll do this. Thanks for picking up where I left @mediaminister
