### ISSUE TITLE
Add logo

### ISSUE THREAD

**Issue by michaelarnauts** [add-ons/plugin.video.viervijfzes#2]
We need a logo and fanart.

**Comment by mediaminister** [comment]
Something like this?

![fanart](https://user-images.githubusercontent.com/45148099/77086591-464aaf80-6a02-11ea-8faf-d1038cd1564c.png)
![icon](https://user-images.githubusercontent.com/45148099/77086593-46e34600-6a02-11ea-9026-ed88bf3ed124.png)

**Comment by michaelarnauts** [comment]
@mediaminister Thanks! Had ook zoiets als geprobeerd, maar was wat "leeg". Hoe ziet die eruit met de logo's in kleur en eventueel wat dichter bijeen zodat ze iets groter zijn?

**Comment by dagwieers** [comment]
Ik had de volgende al eens geprobeerd.
![Screenshot from 2020-03-19 17-47-56](https://user-images.githubusercontent.com/388198/77094711-2f5d8a80-6a0d-11ea-8dff-ed101be6c228.png)
![Screenshot from 2020-03-19 14-38-50](https://user-images.githubusercontent.com/388198/77094718-308eb780-6a0d-11ea-8249-36b16e5da807.png)
![Screenshot from 2020-03-19 13-59-06](https://user-images.githubusercontent.com/388198/77094720-308eb780-6a0d-11ea-9cd6-74312f44ed59.png)

**Comment by mediaminister** [comment]
In kleur en wat groter.

![fanart](https://user-images.githubusercontent.com/45148099/77097710-81081400-6a11-11ea-8d24-f53d8bb6995a.png)
![icon](https://user-images.githubusercontent.com/45148099/77097712-81a0aa80-6a11-11ea-90af-7a79a98bae04.png)

**Comment by mediaminister** [comment]
Meer kleur.

![icon](https://user-images.githubusercontent.com/45148099/77102167-b3693f80-6a18-11ea-9327-226a59d907e1.png)

**Comment by michaelarnauts** [comment]
Thanks. Fixed in afbc2e6
