### ISSUE TITLE
Playback fails directly after entering credentials

### ISSUE THREAD

**Issue by dagwieers** [add-ons/plugin.video.viervijfzes#37]
During the setup of a new Kodi system I noticed this.

When you have just installed the add-on and you play a video, a pop-up appears to ask to enter your credentials, when you follow through and enter the credentials, you get a Kodi error and playback fails.

Playing the same video again does work, so this is a minor issue.

**Comment by michaelarnauts** [comment]
I think I saw this issue when the folder in the addon_data dir wasn't created yet, so it could not save the token. I assume this is the issue here.
