### ISSUE TITLE
Make on-demand available in IPTV manager guide

### ISSUE THREAD

**Issue by pl0ng** [add-ons/plugin.video.viervijfzes#38]
Using:
- Kodi 18.7 windows
- plugin.video.viervijfzes latest
- service.iptv.manager latest

In the IPTV Manager 'channels' view, 4-5-6 is mentioned in the listings. However, they don't provide livestreams.
In the 'guide' view, 4-5-6 are not listed.

Would it be possible to include already broadcasted programs (of that day) in the guide, since they should be available in the on-demand catalogue on the 4/5/6 website?

**Comment by michaelarnauts** [comment]
Hmm, this should already be the case. Can you try to refresh from the IPTV Manager settings?

**Comment by pl0ng** [comment]
Did a refresh to be sure, but problem remains.
The channels are only visible in the 'Channels' (a.k.a. live overview what is currently playing on each channel) view from within the IPTV manager. When I go to the 'Guide' view, for some reason 4-5-6 are not listed.

**Comment by michaelarnauts** [comment]
You can also try to go to the Kodi settings, and under PVR, pick clear all guide data. You can also disable the "cache guide data in database" or something.

I have seen this issue before, and it's something in Kodi, but I can't reproduce it.

**Comment by pl0ng** [comment]
OK, thanks. That fixed the channels being visible in both views now.
Did I understand correctly that I should be able to select & play on-demand items from within the EPG guide? If so, then that is not successful in my setup it seems.

**Comment by michaelarnauts** [comment]
You need to use the context menu on Kodi 18, just selecting it opens the live stream that doesnt exist. There is no way around that.

**Comment by pl0ng** [comment]
Works perfectly. Thanks!
