### ISSUE TITLE
Bug: Unable to start stream from search results

### ISSUE THREAD

**Issue by vermope** [add-ons/plugin.video.viervijfzes#42]
When using the search function within the addon it's not possible to start a program from the found results.

**Comment by vermope** [comment]
After the update to latest build, this seems to work now! I can start any stream from search results.

**Comment by dagwieers** [comment]
Yeah, I reported it privately and it was fixed without an issue ticket. Sorry for that.

**Comment by vermope** [comment]
No problem at all :) Again thank you guys for bringing Belgian TV to Kodi in a way my wife can find everything 🥇
