### ISSUE TITLE
Request: No artwork in main view "A-Z"

### ISSUE THREAD

**Issue by vermope** [add-ons/plugin.video.viervijfzes#43]
There is no artwork in the main view when opening the directory "A - Z" , all underlying directories have artwork.

**Comment by michaelarnauts** [comment]
IIRC, the API call to generate the A-Z listing doesn't provide this, so we use cached metadata and artwork. This will be fetched in the background when this is enabled in the settings.

You should also verify that you are using the latest code, I've fixed an issue with this a week ago. (https://github.com/add-ons/plugin.video.viervijfzes/commit/dcc0a61560cb9907920fea0afcef0d912721396a)

**Comment by vermope** [comment]
@michaelarnauts Works perfect with latest build. Thanks!
