### ISSUE TITLE
Option to hide programs in the catalogue that have only clips or that are not available

### ISSUE THREAD

**Issue by zynx001** [add-ons/plugin.video.viervijfzes#52]
At the moment, there are a lot of programs in the catalogue that can't really be watched because they are either not available or you can only watch one or few clips of the program.

It would be nice if there is an option to hide such programs from the list.

**Comment by michaelarnauts** [comment]
This is something I have thought about, but I can only know if a program has content when it's opened, and by hiding it, you can't open it, and it won't be refreshed.

A different take would be to periodically query all the programs in the background to know if they have content. We only do this for new content currently what we haven't seen before.

**Comment by zynx001** [comment]
First of all; I have no programming knowledge and any suggestion that I make is not based on much useful knowledge. :-) It just seems like a nice function. And thanks for all the work that you guys put in this !

What you say makes sense, and I guess that this "check" would have to be done at the moment that the list of all programs is being generated. Or indeed, periodically in background.

The only thing that I was wondering: on the website of vier, you can recognize the programs that you can watch online, via the the button "kijk online", next to the title. Reading the html code probably ain't the best/most stable approach for something like this. But it would be nice if this were also part of the meta data of the program...

**Comment by michaelarnauts** [comment]
That could be a good idea. We are reading the html already for this listing.

**Comment by michaelarnauts** [comment]
@zynx001 I just noticed, it seems that items without the "kijk online" button can also have programs, like **'t Is gebeurd**, **De Mol**, **De Battle** and probably many others...

**Comment by zynx001** [comment]
> @zynx001 I just noticed, it seems that items without the "kijk online" button can also have programs, like **'t Is gebeurd**, **De Mol**, **De Battle** and probably many others...

Indeed, you are right. I've also done some random checks and found two additional ones; chaussée d'Amour and De wereld van... Bellewaerde.

So apparently, "kijk online" isn't a good indication. 
That's too bad. It would have been too easy... :-)
