### ISSUE TITLE
Submit to Kodi repository

### ISSUE THREAD

**Issue by jimmyd-be** [add-ons/plugin.video.viervijfzes#63]
To let users find this plugin faster it is maybe a goot idea to submit this plugin to the Kodi repository.
Also installing will be a lot easier on all systems.

[Submit to Kodi repo](https://kodi.wiki/view/Submitting_Add-ons)

**Comment by milanmeu** [comment]
This was asked before in issue #61.
Check out this comment to see why it hasn't been submitted yet: https://github.com/add-ons/plugin.video.viervijfzes/issues/61#issuecomment-739503473:
> It hasn't been submitted. The reason is that we don't display ads, and I believe this would be against the terms of use of SBS Belgium.

**Comment by dagwieers** [comment]
I changed the title of  #61 and pinned it as an important issue.

Thanks for your feedback!

**Comment by bertvandepoel** [comment]
I might be wrong, but I was under the impression that the VTMGo Addon also skips ads, and that one is actually included in official repo. It's proving quite challenging as well since there's no convenient way to update the addon except a USB stick, which isn't really to easy to explain to my mum over the phone (after she got cryptic errors with the changing URLs recently), to be fair :P

**Comment by michaelarnauts** [comment]
VTM Go zou wel de advertenties moeten spelen normaal gezien. 

Maar verder, ik heb gisteren een nieuwe 0.4.1 versie uitgebracht, met ondersteuning voor My List en Recommendations, en deze zit vanaf nu ook in de Kodi repository. Normaal gezien zou alles vanzelf moeten updaten.

**Comment by bertvandepoel** [comment]
Kan zeker dat ik me vergis over VTM Go. Misschien hebben we geluk gehad met weinig reclame.

Ik zocht de plugin zonet op https://kodi.tv/addons/browse maar kan hem niet meteen vinden. Onder welke naam zoek ik best?

Alleszins super bedankt voor het insturen en voor alle moeite met het onderhoud van deze plugin!

**Comment by michaelarnauts** [comment]
De website is helaas niet up to date. Gewoon in je Kodi zoeken op GoPlay, en dan zou je die wel moeten vinden.

**Comment by bertvandepoel** [comment]
Ik heb het daarnet getest en de update is inderdaad automatisch uitgevoerd. Erg bedankt! :D
