### ISSUE TITLE
vier.be vijf.be and zestv.be replaced by goplay.be

### ISSUE THREAD

**Issue by dmaes** [add-ons/plugin.video.viervijfzes#65]
https://www.sbsbelgium.be/nieuws/meer-dan-30-vlaamse-gezichten-op-play4play5play6-goplaybe-binnenkort-play7

They changed names and introduced a new website/streaming platform. The old websites all redirect to goplay.be, this Kodi add-on also stopped working (can't add specific error logs at the moment, but might look for them if I got time and if wanted)

**Comment by michaelarnauts** [comment]
See https://github.com/add-ons/plugin.video.viervijfzes/pull/64

**Comment by wputman29** [comment]
@michaelarnauts, last time I checked yesterday, the tv guide didn't sync (yet) and it returned me an error when I refreshed the channels and guides in IPTV Manager, can you confirm that too?

**Comment by MPParsley** [comment]
#64 is merged so we can probably close this.

**Comment by michaelarnauts** [comment]
Correct! I'll probably do a release this week, as soon as I've been able to test it a bit more. Feel free to help with testing and report if it works fine, or if you still see an issue somewhere :)
