### ISSUE TITLE
There's no live stream available for P5

### ISSUE THREAD

**Issue by kingskawn** [add-ons/plugin.video.viervijfzes#88]
Ik heb net de laatste release geprobeerd "plugin.video.viervijfzes-0.4.2.zip" en ik krijg bij het afspelen een foutboodschap "There's no live stream available for P5". Ik zie dat er een andere zip beschikbaar is maar weet niet of deze een betere is: plugin.video.viervijfzes-0.4.2+matrix.1.zip

**Comment by michaelarnauts** [comment]
Dit is geen fout. Er is gewoon geen livestream voor Play4-7, enkel de
on-demand content die je vind op goplay.be.


Op ma 12 apr. 2021 om 09:54 schreef kingskawn ***@***.***>:
