### ISSUE TITLE
Lege catalog

### ISSUE THREAD

**Issue by TwostrokeDesign** [add-ons/plugin.video.viervijfzes#91]
Hallo,

Ik ben een eindgebruiker dus alvast mijn excuses :)

Ik merk dat sinds kort ik de add-on niet meer kan gebruiken.
Versie is up to date (0.4.3+matrix.1), kodi ook.

Ik gebruik een Mi Box (android tv) en de add-on werkte steeds naar behoren.

Probleem:

Als ik de TV Guide of Catalog kies ga ik direct naar Catalogue: Watched  met geen inhoud in de map (enkel ..)
Dit bij alle play kanalen.

Iemand een idee wat de oorzaak kan zijn?

**Comment by TwostrokeDesign** [comment]
Bij deze: https://paste.kodi.tv/ecezitateg

Logingegevens lijken te kloppen (ik kan inloggen op de playmore site bv.

**Comment by DriesBru** [comment]
Hier ook problemen. Wel dingen in de catalogus, maar melding 'er is een fout opgetreden tijdens het aanmelden: user does not exist'.

**Comment by TwostrokeDesign** [comment]
Hey.

Enig nieuws hier rond?

Ondertussen v4.5 maar nog steeds zelfde (luxe) issue :)

**Comment by michaelarnauts** [comment]
@TwostrokeDesign en @DriesBru hebben jullie dit probleem nog steeds? Zeker dat er geen spaties ofzo achter je email staat? Ik kan het niet reproduceren met mijn account. Ik neem aan dat je wel kan inloggen met die account op de website van goplay, en daar iets kan bekijken?

Zou ik nog eens een recente kodi.log kunnen krijgen met debug logging?

Thanks!

**Comment by TwostrokeDesign** [comment]
Mijn app werkt ondertussen weer na een factory reset van de MiBox 4K. Top!

**Comment by DriesBru** [comment]
Die van mij ook op NVIDIA Shield


________________________________

**Comment by michaelarnauts** [comment]
Top. Thanks!
