### ISSUE TITLE
Mijn lijst does load HTML instead of plugin format

### ISSUE THREAD

**Issue by badoneti** [add-ons/plugin.video.viervijfzes#96]
**Describe the bug**
Plugin works but not properly loading "mijn lijst"

**To Reproduce**
1. Open plugin
2. Go to Mijn Lijst
3. list shows old cashed values following a page not found error in logs

**Expected behavior**
List shows current items on Mijn lijst

**Logs**
`2021-10-21 12:33:47.075 T:899      INFO <general>: initializing python engine.
2021-10-21 12:33:47.997 T:899      INFO <general>: CPythonInvoker(8, /storage/.kodi/addons/plugin.video.viervijfzes/addon_entry.py): script successfully run
2021-10-21 12:33:50.264 T:899      INFO <general>: initializing python engine.
2021-10-21 12:33:52.040 T:899     ERROR <general>: [plugin.video.viervijfzes] [resources.lib.viervijfzes.content] <!DOCTYPE html>
                                                   <html lang="nl" dir="ltr">
                                                     <head>
                                                       **<title>Pagina niet gevonden | GoPlay</title>**
                                                       <meta charset="utf-8" />
                                                   <meta name="description" content="Bekijk volledige afleveringen van onze programma&#039;s op GoPlay." />
                                                   <meta property="og:description" content="Bekijk volledige afleveringen van onze programma&#039;s op GoPlay." />
                                                   <meta property="og:image:url" content="https://images.goplay.be/meta/og-qnn3yt.png?auto=format&amp;fit=max&amp;h=630&amp;ixlib=php-1.1.0&amp;q=100&amp;w=1200&amp;s=25b21d1af1e2c009beea14100566bb45" />
                                                   <meta property="og:image:width" content="1200" />
                                                   <meta property="og:image:height" content="630" />
                                                   <meta name="MobileOptimized" content="width" />
                                                   <meta name="HandheldFriendly" content="true" />
                                                   <meta name="viewport" content="width=device-width, height=device-height, initial-scale=1, viewport-fit=cover" />
* omitted for readability full HTML content *
2021-10-21 12:33:52.051 T:899      INFO <general>: Skipped 1 duplicate messages..
2021-10-21 12:33:52.051 T:899   WARNING <general>: [plugin.video.viervijfzes] [resources.lib.viervijfzes.content] Something went wrong when refreshing live data: **Could not fetch data. Using expired cached values.**
2021-10-21 12:33:52.111 T:899      INFO <general>: Skipped 1 duplicate messages..
2021-10-21 12:33:52.111 T:899   WARNING <general>: Invalid media type ""
2021-10-21 12:33:52.117 T:899      INFO <general>: Skipped 1 duplicate messages..
2021-10-21 12:33:52.117 T:899      INFO <general>: CPythonInvoker(8, /storage/.kodi/addons/plugin.video.viervijfzes/addon_entry.py): script successfully run
`
**System**
 - Addon version: 0.4.4+
 - Kodi version: 19.0.1
 - Inputstream adaptive version: 19.0.0.1
 - Operating System: LibreElec

**Comment by michaelarnauts** [comment]
@badoneti I assume you still see this issue? Can you create a kodi.log with debug logging enabled?

**Comment by badoneti** [comment]
Here you go, debug was on although I don't seem to find debug levels in the logs themselves.
[kodi-goplay.log](https://github.com/add-ons/plugin.video.viervijfzes/files/7995107/kodi-goplay.log)

**Comment by michaelarnauts** [comment]
> Here you go, debug was on although I don't seem to find debug levels in the logs themselves. [kodi-goplay.log](https://github.com/add-ons/plugin.video.viervijfzes/files/7995107/kodi-goplay.log)

Interesting, it seems that there are 3 programs on your list, but one of those doesn't seem to be available. How many items do you see on the GoPlay website? I can see De Slimste Mens and Boerenjaar, but there is a 3th also there.

**Comment by badoneti** [comment]
> Interesting, it seems that there are 3 programs on your list, but one of those doesn't seem to be available. How many items do you see on the GoPlay website? I can see De Slimste Mens and Boerenjaar, but there is a 3th also there.

I can see 3 on the GoPlay website: De Slimste Mens, Boerenjaar, Grond. They seem all still available.
I experience a similar issue with VrtNu plugin that favourites are not well syncronized between the website and kodi addon

**Comment by michaelarnauts** [comment]
@badoneti kan je eens proberen met een ZIP uit deze comment? https://github.com/add-ons/plugin.video.viervijfzes/pull/102#issuecomment-1029186413

**Comment by michaelarnauts** [comment]
Fixed in #102
